### PR TITLE
Run user program in firejail

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Add code to run the users programs in firejail with limited network connections specified in `player.net` file that is generated by the supervisor controller (communication port changes at each run).

To make it work correctly it is necessary to setup a network bridge called `br0` in the system.
For example a very simple one can be setup with these instructions:
```
$ sudo apt-get install bridge-utils
$ sudo brctl addbr br0
$ sudo ifconfig br0 10.10.20.1/24 up
```
This is taken from the firejail usage manual: https://firejail.wordpress.com/documentation-2/basic-usage/
When setting the bridge we just have to make sure that the ip we associate to it is not used in the network.
For the moment I also assume that the server machine have a static IP address that can be set in the `config.json`, if not we should read it from the system at each `supervisor` controller run.
The netfilter applied to firejail will then only allow

In any case firejail is only setup in case the variable WEBOTS_FIREJAIL_CONTROLLERS is defined, i.e. when Webots is started by the simulation server but users on their local install won't use it.

### CODE REVIEW

**Comment by omichel** [comment]
127.0.0.1 is local host. If that works with this configuration, do we really need to set a different IP address, given that we don't want to allow controllers to communicate outside of the local host?

**Comment by stefaniapedrazzi** [comment]
127.0.0.1 is a default value, but doesn't work if you set the bridge in firejail.
You need to change it with the IP of the server machine.

**Comment by stefaniapedrazzi** [comment]
127.0.0.1 is the value you need to run the controller without firejail.

**Comment by omichel** [comment]
OK, so in that case, wouldn't it be simpler on the long term to automatically retrieve the IP address of the machine from the supervisor? That would save us from maintaining this configuration file on a per-machine case. That's fairly easy to implement: https://stackoverflow.com/questions/212528/get-the-ip-address-of-the-machine

**Comment by stefaniapedrazzi** [comment]
Yes, I can check if it works.

But first we also have to test it on the test server. For the moment I just tested locally.

**Comment by stefaniapedrazzi** [comment]
In any case the most annoying part is to have to setup the bridge at the computer staart.

**Comment by omichel** [comment]
Yes, this should be automated in some way, so that it's done at each reboot.

**Comment by stefaniapedrazzi** [comment]
Yes we can add it in the starting script of the machine.
But first we have to make sure which IPs are used by the local network and which one can we assign to the bridge.

**Comment by omichel** [comment]
The local network uses addresses in the range 192.168.123.*, so any local network address outside of this is fine.

**Comment by omichel** [comment]
Using 10.10.20.1/24 seems good.

**Comment by stefaniapedrazzi** [comment]
For the one we are using at Cyberbotics.
But this is not always true in local networks, they could also use  IPs starting with 10.

**Comment by omichel** [comment]
Yes...

**Comment by stefaniapedrazzi** [comment]
I added the code to retrieve the IP programmatically and tested on the server machine and it works.

:+1:

**Comment by omichel** [comment]
:eyes:

**Review by omichel — APPROVED** [review]
That looks good to me. Did you try changing the port/IP to check that the connection was indeed blocked?

**Comment by stefaniapedrazzi** [comment]
Yes, I checked locally and on the server.

**Comment by stefaniapedrazzi** [comment]
Do we also have to update the `supervisor` controller signatures?
I didn't commit yet the new controller executables.

**Comment by omichel** [comment]
Yes, we should commit the executable files and corresponding signatures.

**Comment by stefaniapedrazzi** [comment]
I committed the executable and new signature for Linux.

**Comment by stefaniapedrazzi** [comment]
But I'm checking because it doesn't seem to work in Benchmark mode.

**Comment by omichel** [comment]
Do you want me to sign the Windows supervisor binary?

**Comment by stefaniapedrazzi** [comment]
Yes, thank you.

**Comment by stefaniapedrazzi** [comment]
I also updated the world and PROTO files signatures

**Comment by omichel** [comment]
But they didn't change in this PR, isn't it?

**Comment by stefaniapedrazzi** [comment]
No, but they have been modified in #3 and it seems that they were not updates because I couldn't run the simulation in Benchmark mode.

**Comment by stefaniapedrazzi** [comment]
Could you also compile and commit the new Windows executable?
It should have been changed, isn't it?

**Comment by stefaniapedrazzi** [comment]
Thank you

:+1:

**Review by omichel — APPROVED** [review]

**Pull request merged**
