### PR TITLE
Fixed incomplete data read from socket

### PR DESCRIPTION
**Pull request by omichel**
This patch should fix the incomplete data read from socket just reported by @chshong.

👍

### CODE REVIEW

**Comment by chshong** [comment]
Yes, this looks consistently working. I will test on my Windows too

**Comment by chshong** [comment]
On Windows (Windows 10, Python 3.7.3), following error happens

"Received Data: " part is the data received

It looks like the data received cannot be automatically converted to string

```
[supervisor] Traceback (most recent call last):
[supervisor]   File "supervisor.py", line 1377, in <module>
[supervisor]     controller.run()
[supervisor]   File "supervisor.py", line 927, in run
[supervisor]     self.tcp_server.spin(self)
[supervisor]   File "supervisor.py", line 109, in spin
[supervisor]     data += d
[supervisor] TypeError: can only concatenate str (not "bytes") to str
[supervisor] Accepted  ('127.0.0.1', 49917)
[supervisor] Accepted  ('127.0.0.1', 49918)
[supervisor] Received data:  b'aiwc.get_info("kCqtXdMccG")'
```

**Comment by omichel** [comment]
OK, I will fix that. Thank you for the test.

**Comment by omichel** [comment]
I fixed the python 3 problem you reported and tested on both Python 2.7 / Ubuntu 18.04  and Python 3.7 / Windows 10. Can you confirm it works also for you and if so, approve this PR?

👍

**Comment by chshong** [comment]
Yes, the program seems to work properly. Thank you.

**Pull request merged**
