### PR TITLE
Cpp Controller Example

### PR DESCRIPTION
**Pull request by DavidMansolino**
The PR adds a CPP version of the `player_random-walk` controller.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
Status: fully functional remains just a few minor cleanups and TODOs to handle.

**Comment by DavidMansolino** [comment]
:+1:

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Review by stefaniapedrazzi — CHANGES_REQUESTED** [review]
It works fine.
We should just rename the new folder `player_random-walk` to `player_random-walk_cpp`.

**Comment by DavidMansolino** [comment]
:+1:

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you

**Pull request merged**
