### PR TITLE
Fix support of commentator and reporter programs

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
* [x] Fix handling the different roles and fix the support of the commentator and reporter programs.

* [x]  I also added a key for the commentator and reporter so that they can be easily identified and it is possible to prevent calling invalid commands.

* [x]  Implement record game functionality

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
Remaining issues with commentator:
* [x] label text is not correct: i.e. `"G", "a", "m", "e", " ", "h", "a", "s", " ", "b", "e", "g", "u", "n"` instead of `Game has begun`
* [x] sometimes multiple comments written on the same label
* [ ] truncated JSON frames are not handled but simply skipped: the best would be to prevent concatenating frames

**Comment by stefaniapedrazzi** [comment]
Fix game rule issue:
* [x] When the ball is sent out to the corners, the game crashes instead of starting a corner kick.
* [x] When the ball is in blue team's penalty area and more than 3 blue robots are in the area, a penalty kick should start, but the game crashes.
* [x] Sometimes all robots are sent out to the foul area at the same time (I observed this when I manually moved the ball to a goalpost. After the game reset, all robots were sent to the foul zone)

**Comment by stefaniapedrazzi** [comment]
:+1:

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
