### PR TITLE
Fixed Python shebang use for participants programs from supervisor.py

### PR DESCRIPTION
**Pull request by omichel**
This PR fixes (19) from https://github.com/aiwc/test_world/issues/58

When adding new Python participant programs (like in #21), you should be careful to set the execution rights properly to 100755 on the main Python file.

👍

### CODE REVIEW

**Review by chshong — APPROVED** [review]
Works fine

**Review by chshong — COMMENTED** [review]
Actually, I need to check if this works on windows as well

**Review by chshong — APPROVED** [review]
On Windows, the program did not work because Python scripts do not run without calling 'python'. I have fixed the issue and committed the fix. Can you check?

**Comment by omichel** [comment]
Thank you for the fix. I agree with it.

**Pull request merged**
