### PR TITLE
Fix remove boost dependency on soccer robot

### PR DESCRIPTION
**Pull request by omichel**
Addresses item 12 of this [issue](https://github.com/aiwc/test_world/issues/58).

### CODE REVIEW

**Comment by omichel** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Review by stefaniapedrazzi — APPROVED** [review]
I also removed the now useless .gitignore file

**Comment by chshong** [comment]
I think it would be better if we add `from __future__ import division` at the beginning to make sure that divisions are not integer divisions on the program.

**Comment by omichel** [comment]
`from __future__ import division` is needed only with Python 2 when performing a division of an integer with another integer and expecting a float result. This is not the case in `robot_soccer.py`.
The only division in `soccer_robot.py` is [here](https://github.com/omichel/test_world/blob/develop/controllers/soccer_robot/soccer_robot.py#L21) and the second argument is necessarily a float (because `self.noise` is a float). Therefore Python 2 will perform a float division in any case.
So, I am pretty sure the `from __future__ import division` statement is useless.

**Pull request merged**
