### PR TITLE
Fixed termination of participant processes

### PR DESCRIPTION
**Pull request by omichel**
Participant processes in Python were not terminated properly when quitting Webots, causing a useless load on the machine. This PR fixes this issue.

### CODE REVIEW

**Comment by omichel** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Comment by stefaniapedrazzi** [comment]
There are now some conflicts with the PR I just merged. But it works as expected and there are no longer ghost processes.

**Comment by omichel** [comment]
👍

**Review by stefaniapedrazzi — APPROVED** [review]

**Pull request merged**
